[package]
name = "ipld-rs"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of Ipld.lean"

[dependencies]
sha3 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
thiserror = "1.0"
anyhow = "1.0"